services:
  db:
    image: postgres
    container_name: postgresql_container
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ohsansi_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer_container
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:


volumes:
  db-data:
